# -*- coding: utf-8 -*-
"""Neural Network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpVwUbczVuTNdz5abcfqWNgkW6-dbHnw
"""

import numpy as np

inputs = np.array([1.0, 0.5, 0.2])

weights = np.array([0.9, 0.6, 0.1])

weighted_sum = np.dot(inputs, weights)

inputs

weights

weighted_sum

def sigmoid(x):
  return 1 / (1 + np.exp(-x))
output = sigmoid(weighted_sum)
output

