# -*- coding: utf-8 -*-
"""Neural Network tensorflow 1D with Dropout

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCN3o_aGOxuSy6s3VZyUzU9dNN9Tsygy
"""

import tensorflow as tf
from tensorflow.keras import labels, models
import pndas as pd
import matplotlib.pyplot as plt
import seabron as sns
import numpy as np

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets,load_data()

train_images = train_images.astype("float32") / 255
test_images = test_images.astype("float32") / 255

fig, axes = plt.sublotÇ(figsize = (10, 10))

for i in range(10):
  axes[i].imshow(train_images[i].reshape(28, 28), cmap = "gray")
  axes[i].title(train_label[i])
  axes[i].axis("off")
plt.show()

model = models.Sequential([layers.Flatten(input_shape = (28, 28)), layers.Dense(256, activation = "relu"), layers.Dropout(0.3), layers.Dense(128, activation = "relu"), layers.Dropout(0.3), layers.Dense(64, activation = "relu"), layers.Dense(10, activation = "softmax")])

model.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy", metrics = ["accuracy"])
histroy = model.fit(train_images, train_labels, epochs = 5)